name = "gleamql"
version = "0.3.1"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
licences = ["Apache-2.0"]
description = "A Simple Graphql Client Written In Gleam ✨"
repository = { type = "github", user = "cobbinma", repo = "gleamql" }
links = [{ title = "Website", href = "https://gleam.run" }]
gleam = ">= 0.32.0"

[dependencies]
gleam_stdlib = "~> 0.25"
gleam_json = "~> 0.5"
glint = "~> 0.10"

[dev-dependencies]
gleeunit = "~> 0.7"
gleam_hackney = "~> 1.0"
gleam_http = "~> 3.5"
